### PR TITLE
Feature/networking improvements

### PR DESCRIPTION
**Pull request by toabi**
This acutally *also* fixes some small bugs.

But main improvement is that you can also put multiple clusters into one hetzner network.

### CODE REVIEW

**Comment by StarpTech** [comment]
I'll check it today or tomorrow. Very busy at the moment.

**Comment by StarpTech** [comment]
Hi @toabi great additions. Did you run the https://github.com/StarpTech/k-andy/tree/main/example#demo-application with that setup?

**Comment by toabi** [comment]
Uh I didn't think about the /example folder anymore… but I'm using those clusters extensively in a dev environment right now. 

I'll check the example app on monday and maybe even add https://github.com/toabi/k-andy/commit/ce47f2ab34a9cd98dd033b83dae4482162acef94 to it. That's the latest addition we use in our dev clusters.

**Comment by StarpTech** [comment]
> I'll check the example app on monday and maybe even add toabi@ce47f2a to it. That's the latest addition we use in our dev clusters.

:+1:

**Comment by toabi** [comment]
Replaced by #13

**Pull request closed without merging**
