### PR TITLE
feat: convert into terraform module

### PR DESCRIPTION
**Pull request by toabi**
As discussed in #5, this makes it usable as a module. Major changes include:

- SSH key is generated in the module (hcloud only allows unique ssh keys)
- Table in README is created by terraform-docs via [pre-commit](https://pre-commit.com)
- New variable "name" is used to create unique names for resources
- All important other values are exposed via variables
- Some renaming of files and resources

Sure those are a lot of changes at once. Let me know what you think about it.

### CODE REVIEW

**Comment by toabi** [comment]
I added more features in single commits.

**Comment by StarpTech** [comment]
Awesome work! I have some small points:

- Could you add a working example?
- What's necessary to start developing on this repository (some instruction about installing precommit, python etc would be nice)? You can put it in a CONTRIBUTNG.md file.
- It should be possible to pass a custom SSH key. This feature was implemented before.
- You have upgraded the hetzner controller and k3s. Did you test it well?
- If you don't mind you could also create the MIT license file.
- Please output the generated K3S token. This token is useful when restoring the cluster from a backup.

**Comment by toabi** [comment]
I'll do all that tomorrow.

**Comment by toabi** [comment]
- [x] Could you add a working example?
  - I added an `example` folder with things
- [x]  What's necessary to start developing on this repository (some instruction about installing precommit, python etc would be nice)? You can put it in a CONTRIBUTNG.md file.
  - I created a very basic one
- [x]  It should be possible to pass a custom SSH key. This feature was implemented before.
- [x]  You have upgraded the hetzner controller and k3s. Did you test it well?
  - Well… so far I tested the example, but I'll try out more complex things soon.
- [x]  If you don't mind you could also create the MIT license file.
  - I created one with your name
- [x]  Please output the generated K3S token. This token is useful when restoring the cluster from a backup.
  - Also added some output to the example

**Comment by toabi** [comment]
What do you think about enforcing https://www.conventionalcommits.org/en/v1.0.0/#summary from now on in this repository? I personally like it, because one can also autogenerate semantic versions and an okay changelog from them.

**Comment by StarpTech** [comment]
> What do you think about enforcing conventionalcommits.org/en/v1.0.0/#summary from now on in this repository? I personally like it, because one can also autogenerate semantic versions and an okay changelog from them.

I like it too as long as it's automated and ensured. The repo has very low activity, not sure if it is worth it.

**Comment by toabi** [comment]
Jeah, let's leave that for the future.

I think I'm done with the tasks. Everything which was possible in the past is supported. Some parts are even easier (no need for own ssh key). It's a nice base I'll experiment more on. But for the first refactor I think this is a good start.

**Comment by toabi** [comment]
One thing I noticed: replacing servers is not working because of name collision. It's maybe better to add random IDs.

**Comment by StarpTech** [comment]
> One thing I noticed: replacing servers is not working because of name collision. It's maybe better to add random IDs.

Good point. Let's do it.

**Comment by toabi** [comment]
It might even make sense to have a variable where you disable the initial bootstrap control plane and add "normal" agents which join the others. Because the cloud-init of the first one makes sense only once I guess. 
But I have to read a bit more about how the HA k3s control plane works/recovers.

**Comment by StarpTech** [comment]
One small point left: Add `kubeconfig-*`.yaml to gitignore apart from that 👍

**Comment by toabi** [comment]
> One small point left: Add `kubeconfig-*`.yaml to gitignore apart from that 👍

There is https://github.com/toabi/k-andy/blob/feature/modularize/example/.gitignore#L3 - and in the main module it's not necessary because the config will be written where the module is used. It's not necessary anymore to checkout this repository, it can be just in any terraform project as:

```
module "some_cluster" {
  source = "git::https://github.com/toabi/k-andy.git?ref=feature/modularize"
  hcloud_token = "ABC"
  name = "demo"
  server_locations = ["nbg1", "fsn1"]
  agent_server_type = "cx11"
  agent_server_count = 3
  server_additional_packages = ["open-iscsi"]
}
```

**Comment by StarpTech** [comment]
I didn't see it, thanks.

**Pull request merged**
