### PR TITLE
Features: existing networks, agent-groups, upgrade-controller, darwin/arm64 providers, docs

### PR DESCRIPTION
**Pull request by toabi**
Those are some collected changes which we also use in production now.

- Use wireguard
- Make it possible to join existing hcloud networks
- Make it possible to configure taints for agent-groups
- Install upgrade-controller via terraform
- Migrate to all darwin/arm64 compatible provides and remove deprecated ones
- Make it possible to rotate all control-plane nodes and add documentation about it
- Enhance example with some of the features

This fully replaces #13

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi @toabi thanks for the PR.

**Comment by StarpTech** [comment]
We have no automated tests. Did you try the whole setup?

**Comment by toabi** [comment]
I tried the example, and it also runs in our dev cluster so far.
Half of the commits also run already in our staging and production cluster without issues.

It's just not a simple upgrade because you'll have to target-apply existing installation to not roll all nodes at once. But as we don't have any versioning here… that should be fine.

**Comment by StarpTech** [comment]
Thanks for the info.

**Pull request merged**
